# Generated by Django 4.1.3 on 2022-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_email_alter_profile_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
    ]
