# Generated by Django 4.1.3 on 2022-11-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_profile_username_alter_profile_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
    ]
